---
title: "Explanation of GEP, PPFD, Temperature model"
subtitle: "Arikawa Bay, Nagasaki, Japan"  
author: 
  - "Gregory N. Nishihara"
  - "Azusa Kawate"
date: 'Updated `r Sys.Date()`'
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: xaringan-themer.css
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

```{r xaringan-themer, include=FALSE, warning=FALSE}
library(xaringanthemer)
style_duo_accent(
  primary_color = "#1381B0",
  secondary_color = "#FF961C",
  inverse_header_color = "#FFFFFF"
)
```

## The linear model

$$
\begin{aligned}
\log(\mu_{P}) &= f_{cc}(M_i) + f_{tp}(M_i | S_j) + S_j \\
\mu_{T} &= f_{cc}(M_i) + f_{tp}(M_i | S_j) + f_{tp}(M_i | L_k) + S_j + L_k\\
\log(\mu_{G}) &=   \beta_P \mu_P + \beta_T \mu_T + \beta_S S_j + \beta_L L_k \\
\end{aligned}
$$
**Distribution for observations**

$$
\begin{aligned}
y_P &\sim \Gamma(\mu_P / \theta_P, \theta_P) \\
y_T &\sim N(\mu_T, \sigma_T) \\
y_G &\sim \Gamma(\mu_G / \theta_G, \theta_G) \\
\end{aligned}
$$

.pull-left[

* $P$, $T$, $G$: PPFD, Temperature, and GEP
* $M$, $S$, $L$: $i$ Months,  $j$ States, and $k$ Locations
* $f_{cc}$, $f_{tp}$: Cyclic cubic spline and Thin-plate splie

]

.pull-right[
* $y_P$, $y_T$, $y_G$: Observations
* $\theta$, $\sigma$: Scale parameters
* $\mu$:  Location parameter
]

---

## The population and group level effects

$$
\begin{aligned}
\theta_P, \theta_G, \sigma_T       &\sim N(0, 1) \\
\beta_P, \beta_T, \beta_S, \beta_L &\sim N(0, 1) \\
\end{aligned}
$$

---

## BRMS Model

```{r, eval = FALSE}
ppfdmodel = bf(PPFD  ~ s(month, k = 4, bs = "cc") + s(month, by = state) + 
                 state + (0+1|state) +  (0+1|month/state)) + Gamma("log")
tempmodel = bf(TEMP  ~ s(month, k = 6, bs = "cc") + s(month, by = state) + s(month, by = location) + 
                 state + location + (0+1|state/location) + (0 + 1|month/state/location)) + gaussian()
gepmodel  = bf(GEP ~ PPFD + TEMP + state + location + 
                 (0+PPFD+TEMP|state/location) + (0 + 1|month/state/location)) + Gamma("log")
```


```{r, eval = FALSE}

PRIORS = get_prior(completemodel, data = dset) %>% 
  mutate(prior = ifelse(str_detect(class, "b|Intercept|b"),
                        "normal(0, 1)", prior)) %>% 
  mutate(prior = ifelse(str_detect(class, "sd"),
                        "normal(0, 1)", prior)) %>% 
  mutate(prior = ifelse(str_detect(class, "shape|sigma"),
                        "normal(0, 1)", prior)) %>% 
  filter(str_detect(coef, "^s\\(", negate = T))

```

